# Introduction to Scientific Python

Python has become a very popular choice for scientific applications for a few reasons:

- It's free, unlike the main alternative Matlab which is free for students but very expensive for industry
- It's easy to learn and use
- It's very powerful and general purpose, so you can learn Python for numerical studies but use it for making a website
- It has a huge ecosystem of existing packages, creating ever more momentum for the addition of new packages

Python is not without it's downsides though:

- It is actually terrible at numerical stuff!
- It is very slow

These downsides have been mostly addressed by the package called [Numpy](https://numpy.org) which provides Python with a new data type that IS fast. There is also a related package called [Scipy](https://scipy.org) which provides a massive library of functions that operate on Numpy arrays (e.g. Fourier Transforms, ODE solvers, etc).  In fact, many packages have sprouted up around Numpy/Scipy, which are collectively called the "Scipy Stack" (e.g Matplotlib, Pandas, scikit-learn, etc).

> The bottom line is that you need to install both Python and the "Scipy Stack" packages.  This is most conviently done using the [Anaconda Distribution](https://www.anaconda.com/products/distribution).  This distribution is maintained and distributed by a company which was started by the original authors of Numpy.  They make money by providing advanced versions of Anaconda to companies, but they offer the base package for free.  

## Doing Math in Python: The Wrong Way

Let's quickly look at using pure Python to do some basic math. Start by putting some numbers into a ``list``:

In [5]:
a = [1, 2, 3, -2, 0.5]

Now let's mulitply each number by 2:

In [6]:
a = a * 2
print(a)

[1, 2, 3, -2, 0.5, 1, 2, 3, -2, 0.5]


OOPS!  That is not what we wanted.  This illustrates that Python is really not math focused.  Let's do it inside a for-loop:

In [7]:
for i in range(len(a)):
    a[i] = a[i] * 2
print(a)

[2, 4, 6, -4, 1.0, 2, 4, 6, -4, 1.0]


OK, that worked.  But there is one more problem...Python let's us put ANYTHING into ``lists``:

In [8]:
a = [1, 1.0, True, 'one']

Here we have an integer, a float, a boolean, and a string. Trying to do make on this mixed bag will have problems:

In [9]:
for i in range(len(a)):
    a[i] = a[i]*2
print(a)

[2, 2.0, 2, 'oneone']


This did as expected for the integer and float, but it converted the boolean to a integer and did the 'doubling' trick on the string.  What happened here is that Python performed the multiplication of each element differently depending on the type of element.  This required Python to stop and inspect the type of each element, making it slow.  

## Doing Math in Python: The Numpy Way

The slowness of Python comes from the fact that it must inspect each element in a the ``list`` to get its type, then apply the the correct multiplication. Numpy avoids this by offering a new type of ``list`` where all elements are forced to be the same type.  This ``list`` is actually called an ``ndarray`` for N-dimensional array.  Let's see it in action:

In [10]:
import numpy as np
a = np.array([1, 2, 3, 4.0, True], dtype=float)
print(a)

[1. 2. 3. 4. 1.]


Here we have told Numpy that this ``array`` should be of type ``float``, so it converts all values to ``float`` for us.  Now we can do some math:

In [11]:
a = a*2
print(a)

[2. 4. 6. 8. 2.]


All operations in Numpy as done in a 'vectorized' way, meaning everything list done 'element-wise'. There is no need to use a for-loop to scan through the elements, since Numpy will essentially do this for us:

In [12]:
a = 2*a*a + a + 3
print(a)

[ 13.  39.  81. 139.  13.]


## Python's Data Containers

Python's ease of use is one it's main appeals.  This ease of use comes from Python's ability to mix and match data of different types within a single contain, such as the ``list`` we saw above.  In addition to the ``list``, there is also the ``dict`` and ``tuple``. The differences are:

- ``list`` let's you read and write elements using numerical indices
- ``dict`` let's you access elements by name
- ``tuple`` let's you read elements by index, but forbids you from writting. 

There is one additional way to collect data into a bundle: as ``attributes`` of an ``object``. 

Let's quickly explore each of these below:


In [13]:
e = list()
e.append(np.array([1, 3, 4], dtype=int))
e.append(1.0)
e.append('two')
print(e)

[array([1, 3, 4]), 1.0, 'two']


In [14]:
d = dict()
d['dave'] = 1.0
d['bob'] = 1
d['fred'] = True
d['george'] = 'one'
print(d)

{'dave': 1.0, 'bob': 1, 'fred': True, 'george': 'one'}


In [15]:
t = tuple(e)
print(t)

(array([1, 3, 4]), 1.0, 'two')


And finally, let's look at the ``object``:

In [16]:
class NewTypeOfObject:
    pass

In [17]:
obj = NewTypeOfObject()
obj.bob = np.array([1, 3, 5], dtype=float)
obj.dave = 1.0

In [18]:
dir(obj)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'bob',
 'dave']